name: CI

on:
  push:
    branches: [ origin ]
  pull_request:
    branches: [ origin ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn 
        run: |
          yarn 
          yarn test
      - name: yarn example
        working-directory: ./example         
      - run: |
          yarn 
          yarn test
